#设置语言(zh-cn/en-eu)
language: zh-cn
player:
  join:
    # 是否开启登陆消息
    Enable: true
    # 登陆时发送的消息
    Message: 欢迎%player_name%加入服务器
Scoreboard:
  # 是否启用计分板
  Enable: true
  # 计分板标题
  title: CSNKTools
  # 计分板内容
  line:
    - 名称:%player_name%
    - 等级:%player_level%
    - 延迟:%player_ping%
  # 计分板更新时间(tick)
  update: 20
Music:
  Enable: true
  distance: 4
  #云端音乐请输入链接
  qunqing: "https://w.csk.asia/res/nbs/qunqing.nbs"
  #本地音乐请放入music文件夹，链接请填写为www
  badapple: "www"
#反馈功能，使用/ct feedback <主题> <内容> 发送反馈
feedback:
  Enable: true
  email:
    #是否启用邮件提醒（需要配置smtp）
    Enable: false
  #接受提醒的邮箱
    email: expuser@example.com
  #邮件主题,占位符：玩家名称<player_name>,反馈主题<subject>,反馈时间<time>
    subject: "<player_name>提交了反馈<subject>"
website:  #网页
  Enable: false
  #用户信息数据表
  user_table: usertable
  #网页端口
  port: 8080
  #显示目录结构
  dirlist: false
  email:
    #注册邮件的主题
    register_subject: "注册邮件"
#mysql数据库
mysql:
  Enable: false
  #mysql驱动
  drive: "com.mysql.cj.jdbc.Driver" #旧版驱动: com.mysql.jdbc.Driver
  #mysql域名及端口
  host: localhost
  port: 3306
  #数据库名
  database: mydatabase
  #mysql服务器时区
  time: GMT
  #是否使用ssl
  usessl: true
  #编码
  char: UTF-8
  #用户名及密码
  username: myuser
  password: mypassword
#sqlite相关设置
sqlite:
  #sqlite路径，如非必要，请勿更改
  path: "plugins/CSNKTools/data/data.db"
  #玩家数据存储表
  player_data_table: playerData
#邮件系统
smtp:
  Enable: false
  auth: true
  starttls: true
  #smtp服务器
  host: smtp.example.com
  #smtp端口
  port: 587
  #邮箱地址
  username: smtpuser@example.com
  #邮箱密码（授权码）
  password: smtppassword
#服务器开关提示(需要smtp配置)
serverendisable:
  enable: false
  #接收邮件的邮箱地址
  email: expuser@example.com
  #服务器开启时邮件主题
  enable_subject: "服务器启动了"
  #服务器关闭时邮件主题
  disable_subject: "服务器关闭了"
  #是否存储在数据库中
  savedatabase: false
  #表名
  table_name: serverendisable
  #强制使用sqlite
  usesqlite: false