#设置语言(zh-cn/en-eu)
language: zh-cn
player:
  join:
    # 是否开启登陆消息
    Enable: true
    # 登陆时发送的消息
    Message: 欢迎%player_name%加入服务器
Scoreboard:
  # 是否启用计分板
  Enable: true
  # 计分板标题
  title: CSNKTools
  # 计分板内容
  line:
    - 名称:%player_name%
    - 等级:%player_level%
    - 延迟:%player_ping%
  # 计分板更新时间(tick)
  update: 20
Music:
  Enable: true
  distance: 4
  #云端音乐请输入链接
  qunqing: "https://w.csk.asia/res/nbs/qunqing.nbs"
  #本地音乐请放入music文件夹，链接请填写为www
  badapple: "www"
