name: CSNKTools
version: '0.0.2'
main: com.crystalneko.csnktools.csnktools.CSNKTools
api-version: '1.20'
author: CrystalNeko
softdepend: [PlaceholderAPI]
commands:
  csnktools:
    permission: ct.command
    permission-message: §c你没有权限执行这条命令!
    description: CSNKTools命令
    usage: /csnktools
    aliases: [ct, ckt]
