name: CSNKTools
version: '0.1.2'
main: com.crystalneko.csnktools.CSNKTools
api-version: '1.20'
author: CrystalNeko
softdepend:
  - PlaceholderAPI
  - NoteBlockAPI
commands:
  csnktools:
    description: CSNKTools命令
    usage: /csnktools
    aliases: [ct, ckt]
  csnktoolsadmin:
    description: CSNKTools命令
    usage: /csnktoolsadmin
    aliases: [cta, ckta]
permissions:
  ct.command:
    description: 允许使用/ct命令
    default: true
  ct.command.help:
    description: 允许使用/ct help命令
    default: true
  ct.command.about:
    description: 允许使用/ct about命令
    default: true
  ct.command.check:
    description: 允许使用/ct check命令
    default: true
  ct.command.playsound:
    description: 允许使用/ct playsound命令
    default: true
  ct.command.feedback:
    description: 允许使用/ct feedback命令
    default: true
  cta.command.help:
    description: 允许使用/cta help命令
    default: false
  cta.command.download:
    description: 允许使用/cta download命令
    default: false

